import { useMemo } from "react";
import { CheckCircle2, AlertTriangle, Target, Copy, Download, Sparkles } from "lucide-react";
import { toast } from "sonner";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useMomentum } from "./MomentumContext";

export function WeeklySummaryDialog({
  open,
  onOpenChange,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
}) {
  const { goals } = useMomentum();

  const { completed, bottlenecks, focus, plainText } = useMemo(() => {
    const completed = goals
      .filter((g) => g.progress >= 75)
      .map((g) => `${g.title} — ${g.progress}% complete`);
    const bottlenecks = goals
      .filter((g) => g.risk === "At Risk" || g.risk === "Critical")
      .map((g) => `${g.title} (${g.risk}) — ${g.insight}`);
    const focus = goals
      .filter((g) => g.priority === "High" && g.progress < 90)
      .slice(0, 4)
      .map((g) => `Push ${g.title} — target ${g.target}`);

    const week = new Date().toLocaleDateString(undefined, {
      month: "short",
      day: "numeric",
    });
    const plainText = [
      `Momentum AI · Weekly Executive Summary (${week})`,
      "",
      "Completed Milestones:",
      ...(completed.length ? completed.map((s) => `  • ${s}`) : ["  • No major milestones crossed this week."]),
      "",
      "High-Risk Bottlenecks:",
      ...(bottlenecks.length ? bottlenecks.map((s) => `  • ${s}`) : ["  • All goals within tolerance."]),
      "",
      "Recommended Focus — Next Week:",
      ...(focus.length ? focus.map((s) => `  • ${s}`) : ["  • Maintain current cadence."]),
    ].join("\n");

    return { completed, bottlenecks, focus, plainText };
  }, [goals]);

  function copy() {
    navigator.clipboard.writeText(plainText);
    toast.success("Summary copied to clipboard");
  }

  function download() {
    const blob = new Blob([plainText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "momentum-weekly-summary.txt";
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Summary downloaded");
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <div className="flex items-center gap-2 text-xs uppercase tracking-widest text-primary">
            <Sparkles className="h-3.5 w-3.5" />
            Generated by Momentum
          </div>
          <DialogTitle className="text-2xl">AI Weekly Executive Summary</DialogTitle>
          <DialogDescription>
            A synthesized recap of this week's execution across your portfolio.
          </DialogDescription>
        </DialogHeader>

        <div className="mt-2 max-h-[55vh] space-y-5 overflow-y-auto pr-1">
          <Section
            icon={<CheckCircle2 className="h-4 w-4 text-emerald-400" />}
            title="Completed Milestones"
            items={completed}
            empty="No major milestones crossed this week."
          />
          <Section
            icon={<AlertTriangle className="h-4 w-4 text-amber-400" />}
            title="High-Risk Bottlenecks"
            items={bottlenecks}
            empty="All goals within tolerance."
          />
          <Section
            icon={<Target className="h-4 w-4 text-primary" />}
            title="Recommended Focus — Next Week"
            items={focus}
            empty="Maintain current cadence."
          />
        </div>

        <div className="mt-4 flex flex-wrap justify-end gap-2 border-t border-border pt-4">
          <Button variant="outline" onClick={copy}>
            <Copy className="h-4 w-4" />
            Copy summary
          </Button>
          <Button onClick={download} className="bg-gradient-primary text-primary-foreground shadow-glow">
            <Download className="h-4 w-4" />
            Download
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}

function Section({
  icon,
  title,
  items,
  empty,
}: {
  icon: React.ReactNode;
  title: string;
  items: string[];
  empty: string;
}) {
  return (
    <div className="rounded-lg border border-border bg-card/60 p-4">
      <div className="flex items-center gap-2 text-sm font-medium">
        {icon}
        {title}
      </div>
      <ul className="mt-3 space-y-1.5 text-sm text-muted-foreground">
        {items.length ? (
          items.map((s, i) => (
            <li key={i} className="flex gap-2">
              <span className="mt-1.5 h-1 w-1 shrink-0 rounded-full bg-primary" />
              <span>{s}</span>
            </li>
          ))
        ) : (
          <li className="italic">{empty}</li>
        )}
      </ul>
    </div>
  );
}
